import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./Components/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  // title: "Create Next App", 
  // description: "Generated by create next app",


  title: "CalebDesigns – Top Web Design in Lagos & Nigeria",
  description: "Professional, innovative, and dependable! Caleb Designs transformed our ideas into stunning, functional designs. Their attention to detail and creativity perfectly aligned with our vision. Highly recommended for anyone seeking design excellence!",
  keywords: ["Web Design Services", "Custom Web Design", "E-commerce Websites", "SEO Services", "Website Management", "Social Media Management", "Web Hosting Services", "Online Business Solutions", "Website Development", "User Experience (UX) Design", "Responsive Web Design"],
  openGraph: {
    title: "CalebDesigns – Top Web Design in Lagos & Nigeria",
    description: "Caleb Designs is a web design agency specializing in building stunning, responsive websites for businesses.",
    url: "https://calebdesigns.vercel.app/",
    siteName: "CalebDesigns",
    images: [
      {
        url: "/src/images/EdTech.png", // Path to your Open Graph image in public folder
        width: 1200,
        height: 630,
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "CalebDesigns – Top Web Design in Lagos & Nigeria",
    description: "Caleb Designs is a web design agency specializing in building stunning, responsive websites for businesses.",
    images: ["/src/images/EdTech.png"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} max-w-2xl mx-auto antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
