import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./Components/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  // title: "Create Next App",
  // description: "Generated by create next app",

  title: "CalebDesigns – Expert Web Design in Lagos, Nigeria",
  description:
    "Caleb Designs creates stunning, responsive websites for startups across Africa. Let us build your business a beautiful online presence.",
  alternates: {
    canonical: "https://calebdesigns.vercel.app/",
  },
  keywords: [
    "Web Design Services",
    "Custom Web Design",
    "E-commerce Websites",
    "SEO Services",
    "Website Management",
    "Social Media Management",
    "Web Hosting Services",
    "Online Business Solutions",
    "Website Development",
    "User Experience (UX) Design",
    "Responsive Web Design",
  ],
  openGraph: {
    title: "CalebDesigns – Top Web Design in Lagos & Nigeria",
    description:
      "Caleb Designs creates stunning, responsive websites for startups across Africa. Let us build your business a beautiful online presence.",
    url: "https://calebdesigns.vercel.app/",
    siteName: "CalebDesigns",
    images: [
      {
        url: "https://calebdesigns.vercel.app/EdTech.png", // Path to your Open Graph image in public folder
        width: 1200,
        height: 630,
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "CalebDesigns – Top Web Design in Lagos & Nigeria",
    description:
      "Caleb Designs creates stunning, responsive websites for startups across Africa. Let us build your business a beautiful online presence.",
    images: ["https://calebdesigns.vercel.app/EdTech.png"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <meta
          name="p:domain_verify"
          content="6b63cbebde4f0d3a7bff184d7942c48a"
        />
      </head>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} max-w-2xl mx-auto antialiased bg-[#0a0a0a]`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
